port: 7880
bind_addresses:
  - 0.0.0.0

keys:
  devkey: secret

user_auth:
  jwt_secret: "stream-hub-dev-secret-key-at-least-32chars!"
  token_expiry: 24h
  min_username_length: 3
  min_password_length: 6

redis:
  address: localhost:6379

postgres:
  host: localhost
  port: 5432
  user: streamhub
  password: streamhub
  database: streamhub
  ssl_mode: disable
  max_conns: 10

development: true


logging:
  level: info
